FROM ethereum/client-go

RUN apk add --update git bash nodejs nodejs-npm perl

RUN cd /root &&\
    git clone https://github.com/cubedro/eth-net-intelligence-api &&\
    cd eth-net-intelligence-api &&\
    npm install &&\
    npm install -g pm2

ADD pass.txt /root/files/password.txt
ADD genesis.json /root/files/genesis.json
ADD localtime /etc/localtime
ADD keystore /root/.ethereum/devchain/keystore

ADD start.sh /root/start.sh
ADD app.json /root/eth-net-intelligence-api/app.json
RUN chmod +x /root/start.sh

ENTRYPOINT /root/start.sh
