version: "2"
services:
#--------------------------------- Bootstarp
  bootstrap:
    build: monitored-geth-client
    restart: on-failure
    container_name: bootstrap
    hostname: bootstrap
    links:
      - netstats
    entrypoint: /root/start.sh
    command: '--datadir=~/.ethereum/devchain --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322  --syncmode "full" --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=1212 --rpc --rpcaddr="0.0.0.0" --gasprice "0"'
    ports:
      - "30303:30303"
      - "30303:30303/udp"
      - "8545:8545"

#--------------------------------- M1
  eth-miner1:
    build: monitored-geth-client
    restart: on-failure
    links:
      - bootstrap
      - netstats
    entrypoint: /root/start.sh
    command: '--datadir=~/.ethereum/devchain --port 30311 --syncmode "full" --rpccorsdomain="*" --networkid=1212 --rpc --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@XXX:30303" --gasprice "0" --etherbase "0" -unlock "0" --password /root/files/password.txt  --mine'
    ports:
      - "30311:30311"

#--------------------------------- M2
  eth-miner2:
    build: monitored-geth-client
    restart: on-failure
    links:
      - bootstrap
      - netstats
    entrypoint: /root/start.sh
    command: '--datadir=~/.ethereum/devchain --syncmode "full" --port 30312 --rpccorsdomain="*" --networkid=1212 --rpc --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@XXX:30303" --gasprice "0" --etherbase "1" -unlock "1" --password /root/files/password.txt --mine'
    ports:
      - "30312:30312"

#--------------------------------- M3
  eth-miner3:
    build: monitored-geth-client
    restart: on-failure
    container_name: eth-miner3
    links:
      - bootstrap
      - netstats
    entrypoint: /root/start.sh
    command: '--datadir=~/.ethereum/devchain --syncmode "full" --port 30313 --rpccorsdomain="*" --networkid=1212 --rpc --bootnodes="enode://288b97262895b1c7ec61cf314c2e2004407d0a5dc77566877aad1f2a36659c8b698f4b56fd06c4a0c0bf007b4cfb3e7122d907da3b005fa90e724441902eb19e@XXX:30303" --gasprice "0" --etherbase "2" -unlock "2" --password /root/files/password.txt --mine'
    ports:
      - "30313:30313"

#--------------------------------- Net Stats
  netstats:
    build: eth-netstats
    restart: on-failure
    container_name: netstats
    environment:
      - WS_SECRET=eth-net-stats-secret
    ports:
      - "3000:3000"

